services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: libreshelf
      POSTGRES_PASSWORD: libreshelf
      POSTGRES_DB: libreshelf
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    volumes:
      - ./books:/app/books
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
