services:
  libreshelf-backend:
    build: ./backend
    container_name: libreshelf-backend
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://admin:changeme@libreshelf-db/libreshelf
    volumes:
      - ./volumes/local:/app/books/local
      - ./volumes/shared:/app/books/shared
      - ./volumes/other:/app/books/other
      - ./config:/app/config
    depends_on:
      - libreshelf-db

  libreshelf-frontend:
    build: ./frontend
    container_name: libreshelf-frontend
    ports:
      - "3000:3000"
    depends_on:
      - libreshelf-backend

  libreshelf-db:
    image: postgres:15
    container_name: libreshelf-db
    environment:
      POSTGRES_DB: libreshelf
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: changeme
    volumes:
      - libreshelf_db_data:/var/lib/postgresql/data

volumes:
  libreshelf_db_data:
