version: "3.9"

services:
  libreshelf-db:
    image: postgres:13
    environment:
      POSTGRES_USER: libreshelf
      POSTGRES_PASSWORD: libreshelf
      POSTGRES_DB: libreshelf
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - libreshelf-net

  libreshelf-backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://libreshelf:libreshelf@libreshelf-db:5432/libreshelf
    depends_on:
      - libreshelf-db
    networks:
      - libreshelf-net

  libreshelf-frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - libreshelf-backend
    networks:
      - libreshelf-net

volumes:
  db_data:

networks:
  libreshelf-net:
