services:
  libreshelf-db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: libreshelf
      POSTGRES_USER: libreshelf
      POSTGRES_PASSWORD: libreshelf
    volumes:
      - libreshelf-db-data:/var/lib/postgresql/data
    networks:
      - libreshelf-net

  libreshelf-backend:
    build:
      context: ./backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://libreshelf:libreshelf@libreshelf-db:5432/libreshelf
    depends_on:
      - libreshelf-db
    volumes:
      - ./books/local:/app/books/local
      - ./books/shared:/app/books/shared
    networks:
      - libreshelf-net

  libreshelf-frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    depends_on:
      - libreshelf-backend
    ports:
      - "3000:3000"
    networks:
      - libreshelf-net

volumes:
  libreshelf-db-data:

networks:
  libreshelf-net:
