services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./books:/app/books
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 5s
      timeout: 3s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: libreshelf
      POSTGRES_PASSWORD: libreshelf
      POSTGRES_DB: libreshelf
    volumes:
      - libreshelf_db_data:/var/lib/postgresql/data

volumes:
  libreshelf_db_data:
