services:
  backend:
    build: ./backend
    volumes:
      - ./books:/books
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: books
      POSTGRES_USER: books
      POSTGRES_DB: books
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
