services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./books:/app/books
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=4000

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: libreshelf
      POSTGRES_PASSWORD: libreshelf
      POSTGRES_DB: libreshelf
    volumes:
      - libreshelf_db_data:/var/lib/postgresql/data

volumes:
  libreshelf_db_data:
