services:
  backend:
    build: ./backend
    container_name: libreshelf-backend
    volumes:
      - ./volumes/local:/app/books/local
      - ./volumes/shared:/app/books/shared
      - ./volumes/other:/app/books/other
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    container_name: libreshelf-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes: {}
