# Build stage
FROM node:20-bullseye AS builder
RUN corepack enable && corepack prepare npm@11.2.0 --activate
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# Production server
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
